geASFProcess/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views 
from django.views.static import serve
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('',views.homepage_view, name="home"),
    path('users/', include('users.urls')),
    path('tasks/', include('tasks.urls')),
    
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('rem-upc/', views.remupc_view, name="rem-upc"),
    path('download/', views.download_files, name='download'),
    path('reports/', views.reports_view, name='reports'),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('help/', views.helppage_view, name="help"),
]

templates/home.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
  Reports
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/body-style.css' %}">

  <div class="container-home">
    <div class="home-box">
    
        <div class = "home-quote">
        <p>
            <h4>&#10077;&nbsp;Safety Begins With You <br>
            Respect the Risk<br>
            See It... Own It...<br>
            Step Up, Speak Out, and Listen&nbsp;&#10078;</h4>
        </p>
        </div>

      {% comment %} <h1>Report Viewer</h1> {% endcomment %}
    </div>
  </div>
{% endblock %}

templates/layout-login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"/> -->
    <link href="https://cdn.jsdelivr.net/npm/remixicon@3.2.0/fonts/remixicon.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style-login.css' %}">
    <link rel="icon" href="{% static 'img/web-icon.png' %}" type="image/x-icon">
    
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">

    <script src="{% static 'js/main.js' %}" defer></script>


    <title>
      
        {% block title %}
            GE ASF Company
        {% endblock %}
    </title>


</head>
<body>

          <!--=============== HEADER ===============-->
          <header class="header">
            <nav class="nav container">
               <div class="nav__data">
                  
                  <a href="" class="nav__logo">
                     <img src="{% static 'img/ge-logo-rect.png' %}" alt="Giant Eagle Logo" id = "header" class="img-logo">
                     <!-- <i class="ri-planet-line1"> </i> -->
                     &nbsp; &nbsp;  ASF Company                    
                  </a>
                  
                  <div class="nav__toggle" id="nav-toggle">
                     <i class="ri-menu-line nav__burger"></i>
                     <i class="ri-close-line nav__close"></i>
                  </div>
               </div>
   
               
               <!--=============== NAV MENU ===============-->
               <div class="nav__menu {% if disable_menu %}disabled-menu{% endif %}" id="nav-menu">
                  <ul class="nav__list">
                    
                     <li><a href="/" class="nav__link">
                        <i class="ri-home-heart-line"></i>&nbsp;Home
                     </a></li>
                     
                    {% if user.is_authenticated %}
                     <!--=============== DROPDOWN 1 ===============-->
                     <li class="dropdown__item">
                        <div class="nav__link">
                           Bin Work <i class="ri-arrow-down-s-line dropdown__arrow"></i>
                        </div>
   
                        <ul class="dropdown__menu">
                           <li>
                              <a href="#" class="dropdown__link">
                                 <i class="ri-folder-settings-line"></i> General
                              </a>                          
                           </li>
   
                           <li>
                              <a href="#" class="dropdown__link">
                                 <i class="ri-markdown-line"></i> Misc Work
                              </a>
                           </li>

                        </ul>
                     </li>


                   <!--=============== DROPDOWN 1 ===============-->
                   <li class="dropdown__item">
                     <div class="nav__link">
                        DI/CP <i class="ri-arrow-down-s-line dropdown__arrow"></i>
                     </div>

                     <ul class="dropdown__menu">
                        <li>
                           <a href="#" class="dropdown__link">
                              <i class="ri-database-line"></i> Data Integrity
                           </a>                          
                        </li>

                        <li>
                           <a href="#" class="dropdown__link">
                              <i class="ri-arrow-up-down-line"></i> Central Processing
                           </a>
                        </li>

                        <!--=============== DROPDOWN SUBMENU ===============-->
                        <li class="dropdown__subitem">
                           <div class="dropdown__link">
                              <i class="ri-price-tag-2-line"></i> Tag Requests <i class="ri-add-line dropdown__add"></i>
                           </div>

                           <ul class="dropdown__submenu">
                              <li>
                                 <a href="#" class="dropdown__sublink">
                                    <i class="ri-price-tag-line"></i> Regular Tags
                                 </a>
                              </li>
      
                              <li>
                                 <a href="#" class="dropdown__sublink">
                                    <i class="ri-price-tag-3-line"></i> Reset Tags
                                 </a>
                              </li>
      
                              <li>
                                 <a href="#" class="dropdown__sublink">
                                    <i class="ri-coupon-line"></i> Coupons
                                 </a>
                              </li>
                           </ul>
                        </li>
                     </ul>
                  </li>


                   <!--=============== DROPDOWN 1 ===============-->
                     <li class="dropdown__item">
                        <div class="nav__link">
                           PER/FIN <i class="ri-arrow-down-s-line dropdown__arrow"></i>
                        </div>
   
                        <ul class="dropdown__menu">
                           <li>
                              <a href="#" class="dropdown__link">
                                 <i class="ri-shopping-cart-line"></i> Perishable
                              </a>                          
                           </li>
   
                           <li>
                              <a href="#" class="dropdown__link">
                                 <i class="ri-exchange-dollar-line"></i> Financial
                              </a>
                           </li>

                           <li>
                              <a href="#" class="dropdown__link">
                                 <i class="ri-cash-line"></i> Pricing
                              </a>
                           </li>
   
                        </ul>
                     </li>


                     <!--=============== DROPDOWN 1 ===============-->
                     <li class="dropdown__item">
                        <div class="nav__link">
                           <i class="ri-printer-cloud-line"></i> 
                           Print Team 
                           <i class="ri-arrow-down-s-line dropdown__arrow"></i>
                        </div>
   
                        <ul class="dropdown__menu">
                           <li>
                              <a href="#" class="dropdown__link">
                                 <i class="ri-printer-line"></i> General
                              </a>                          
                           </li>
   
                           <li>
                              <a href= "{% url 'tasks:rem-upc' %}" class="dropdown__link">
                                 <i class="ri-delete-row"></i> Remove UPC
                              </a>
                           </li>

                        </ul>
                     </li>

                     {% endif %}
                     
                     <!--=============== DROPDOWN 2 ===============-->
                     <li class="dropdown__item">
                        <div class="nav__link">
                           <i class="ri-user-line"></i> User <i class="ri-arrow-down-s-line dropdown__arrow"></i>
                        </div>
   
                        <ul class="dropdown__menu">

                           {% if not user.is_authenticated %}
                           <li>
                              <a href="{% url 'users:login' %}" class="dropdown__link">
                                 <i class="ri-lock-line"></i> Login
                              </a>                          
                           </li>

                           {% else %}

                              {% if user.is_superuser or 'GRP_RU' in request.session.user_groups %}                             
                              <li>
                                 <a href="{% url 'users:register' %}" class="dropdown__link">
                                    <i class="ri-registered-line"></i> Register
                                 </a>                          
                              </li>
                              {% endif %}

                          
                           <li>
                              <a href="#" class="dropdown__link">
                                 <i class="ri-profile-line"></i> Profiles
                              </a>                          
                           </li>
   
                           <li>
                              <a href="#" class="dropdown__link">
                                 <i class="ri-lock-password-line"></i> Change Password
                              </a>
                           </li>
   
                           <li>
                              
                              {% comment %} <a href="{% url 'users:logout' %}" class="dropdown__link">
                                 <i class="ri-lock-unlock-line"></i> Log out
                              </a>  {% endcomment %}

                              <form class="dropdown__link" action="{% url 'users:logout' %}" method="post">
                                 {% csrf_token %}
                                 <button type="submit" class="dropdown__link">
                                     <i class="ri-lock-unlock-line"></i> Log out
                                 </button>
                             </form>

                           </li>

                           {% endif %}

                        </ul>
                     </li>
   
                     <li><a href="{% url 'users:help' %}" class="nav__link">
                        <i class="ri-customer-service-2-line"></i> Help
                     </a></li>
                  </ul>
               </div>
               
            </nav>
         </header>
   
   <main>
      {% block content %}
         Main body content
      {% endblock %}
   </main>

         <!--=============== MAIN JS ===============-->
        <!-- <script src="assets/js/main.js"></script>-->
         <script src="{% static 'js/main.js' %}" defer></script>

</body>
</html>

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"/> -->
    <link href="https://cdn.jsdelivr.net/npm/remixicon@3.2.0/fonts/remixicon.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'img/web-icon.png' %}" type="image/x-icon">
    <script src="{% static 'js/main.js' %}" defer></script>


    <title>
      
        {% block title %}
            GE ASF Company
        {% endblock %}
    </title>


</head>
<body>

          <!--=============== HEADER ===============-->
          <header class="header">
            <nav class="nav container">
               <div class="nav__data">
                  
                  <a href="" class="nav__logo">
                     <img src="{% static 'img/ge-logo-rect.png' %}" alt="Giant Eagle Logo" id = "header" class="img-logo">
                     <!-- <i class="ri-planet-line1"> </i> -->
                     &nbsp; &nbsp;  ASF Company                    
                  </a>
                  
                  <div class="nav__toggle" id="nav-toggle">
                     <i class="ri-menu-line nav__burger"></i>
                     <i class="ri-close-line nav__close"></i>
                  </div>
               </div>
               
               
               <!--=============== NAV MENU ===============-->
               <div class="nav__menu {% if disable_menu %}disabled-menu{% endif %}" id="nav-menu">
                  <ul class="nav__list">
                    
                     <li><a href="/" class="nav__link">
                        <i class="ri-home-heart-line"></i>&nbsp;Home
                     </a></li>
                     
                  {% if user.is_authenticated %}
                     <!--=============== DROPDOWN 1 ===============-->
                     {% if user.is_superuser or 'GRP_BW' in request.session.user_groups or 'GRP_AL' in request.session.user_groups %}    
                     <li class="dropdown__item">
                        <div class="nav__link">
                           Bin Work <i class="ri-arrow-down-s-line dropdown__arrow"></i>
                        </div>
   
                        <ul class="dropdown__menu">
                           <li>
                              <a href="#" class="dropdown__link">
                                 <i class="ri-folder-settings-line"></i> General
                              </a>                          
                           </li>
   
                           <li>
                              <a href="#" class="dropdown__link">
                                 <i class="ri-markdown-line"></i> Misc Work
                              </a>
                           </li>

                        </ul>
                     </li>
                     {% endif %}

                   <!--=============== DROPDOWN 1 ===============-->
                   {% if user.is_superuser or 'GRP_DC' in request.session.user_groups or 'GRP_AL' in request.session.user_groups %}    
                   <li class="dropdown__item">
                     <div class="nav__link">
                        DI/CP <i class="ri-arrow-down-s-line dropdown__arrow"></i>
                     </div>

                     <ul class="dropdown__menu">
                        <li>
                           <a href="#" class="dropdown__link">
                              <i class="ri-database-line"></i> Data Integrity
                           </a>                          
                        </li>

                        <li>
                           <a href="#" class="dropdown__link">
                              <i class="ri-arrow-up-down-line"></i> Central Processing
                           </a>
                        </li>

                        <!--=============== DROPDOWN SUBMENU ===============-->
                        <li class="dropdown__subitem">
                           <div class="dropdown__link">
                              <i class="ri-price-tag-2-line"></i> Tag Requests <i class="ri-add-line dropdown__add"></i>
                           </div>

                           <ul class="dropdown__submenu">
                              <li>
                                 <a href="#" class="dropdown__sublink">
                                    <i class="ri-price-tag-line"></i> Regular Tags
                                 </a>
                              </li>
      
                              <li>
                                 <a href="#" class="dropdown__sublink">
                                    <i class="ri-price-tag-3-line"></i> Reset Tags
                                 </a>
                              </li>
      
                              <li>
                                 <a href="#" class="dropdown__sublink">
                                    <i class="ri-coupon-line"></i> Coupons
                                 </a>
                              </li>
                           </ul>
                        </li>

                        <!--=============== DROPDOWN SUBMENU ===============-->
                        <li class="dropdown__subitem">
                           <div class="dropdown__link">
                              <i class="ri-price-tag-2-line"></i> Reports <i class="ri-add-line dropdown__add"></i>
                           </div>

                           <ul class="dropdown__submenu">
                              <li>
                                 <a href="{% url 'tasks:reports' %}" class="dropdown__sublink">
                                    <i class="ri-price-tag-2-line"></i> Report 1
                                 </a>
                              </li>
      
                              <li>
                                 <a href="#" class="dropdown__sublink">
                                    <i class="ri-price-tag-2-line"></i> Report 2
                                 </a>
                              </li>
      
                           </ul>
                        </li>

                     </ul>
                  </li>
                  {% endif %}

                   <!--=============== DROPDOWN 1 ===============-->
                   {% if user.is_superuser or 'GRP_PF' in request.session.user_groups or 'GRP_AL' in request.session.user_groups %}    
                  <li class="dropdown__item">
                     <div class="nav__link">
                        PER/FIN <i class="ri-arrow-down-s-line dropdown__arrow"></i>
                     </div>

                     <ul class="dropdown__menu">
                        <li>
                           <a href="#" class="dropdown__link">
                              <i class="ri-shopping-cart-line"></i> Perishable
                           </a>                          
                        </li>

                        <li>
                           <a href="#" class="dropdown__link">
                              <i class="ri-exchange-dollar-line"></i> Financial
                           </a>
                        </li>

                        <li>
                           <a href="#" class="dropdown__link">
                              <i class="ri-cash-line"></i> Pricing
                           </a>
                        </li>

                     </ul>
                  </li>
                  {% endif %}

                  <!--=============== DROPDOWN 1 ===============-->
                  {% if user.is_superuser or 'GRP_PT' in request.session.user_groups or 'GRP_AL' in request.session.user_groups %}  
                  <li class="dropdown__item">
                     <div class="nav__link">
                        <i class="ri-printer-cloud-line"></i> 
                        Print Team 
                        <i class="ri-arrow-down-s-line dropdown__arrow"></i>
                     </div>

                     <ul class="dropdown__menu">
                        <li>
                           <a href="#" class="dropdown__link">
                              <i class="ri-printer-line"></i> General
                           </a>                          
                        </li>

                        <li>
                           <a href= "{% url 'tasks:rem-upc' %}" class="dropdown__link">
                              <i class="ri-delete-row"></i> Remove UPC
                           </a>
                        </li>

                     </ul>
                  </li>
                  {% endif %}

               {% endif %}
                     
                     <!--=============== DROPDOWN 2 ===============-->
                     <li class="dropdown__item">
                        <div class="nav__link">
                           <i class="ri-user-line"></i> User <i class="ri-arrow-down-s-line dropdown__arrow"></i>
                        </div>
   
                        <ul class="dropdown__menu">

                           {% if not user.is_authenticated %}
                           <li>
                              <a href="{% url 'users:login' %}" class="dropdown__link">
                                 <i class="ri-lock-line"></i> Login
                              </a>                          
                           </li>
                           {% else %}

                              {% if user.is_superuser or 'GRP_RU' in request.session.user_groups %}                             
                              <li>
                                 <a href="{% url 'users:register' %}" class="dropdown__link">
                                    <i class="ri-registered-line"></i> Register
                                 </a>                          
                              </li>
                              {% endif %}
                           
                          
                           <li>
                              <a href="#" class="dropdown__link">
                                 <i class="ri-profile-line"></i> Profiles
                              </a>                          
                           </li>
   
                           <li>
                              <a href="#" class="dropdown__link">
                                 <i class="ri-lock-password-line"></i> Change Password
                              </a>
                           </li>
   
                           <li>
                              
                              {% comment %} <a href="{% url 'users:logout' %}" class="dropdown__link">
                                 <i class="ri-lock-unlock-line"></i> Log out
                              </a>  {% endcomment %}

                              <form class="dropdown__link" action="{% url 'users:logout' %}" method="post">
                                 {% csrf_token %}
                                 <button type="submit" class="dropdown__link">
                                     <i class="ri-lock-unlock-line"></i> Log out
                                 </button>
                             </form>

                           </li>

                           {% endif %}

                        </ul>
                     </li>
   
                     <li><a href="{% url 'users:help' %}" class="nav__link">
                        <i class="ri-customer-service-2-line"></i> Help
                     </a></li>
                  </ul>
               </div>
            
            </nav>
         </header>
   
   <main>
      {% block content %}
         Main body content
      {% endblock %}
   </main>
         <!--=============== MAIN JS ===============-->
        <!-- <script src="assets/js/main.js"></script>-->
         <script src="{% static 'js/main.js' %}" defer></script>


</body>
</html>